### ISSUE TITLE
Please check parallel benchmarking blog post

### ISSUE THREAD

**Issue by HeidiSeibold** [mlr-org/mlr-org.github.io#13]
2017-03-03-parallel-benchmarking.Rmd

- Is text easy to understand?
- Any language errors?
- Anything that should be added / done differently?
- Can I keep `parallel_benchmarking_blogpost_results.rds` in `_source/` or is that against the rules?

I know that you know this but as a reminder to myself:
If all is okay, change name of file (date to current date), delete `draft: true` and render.

**Comment by jakob-r** [comment]
The rds file should be called like the Rmd file so that we see what belongs together.
The Rmd file should be called like the title of your blog post.

Please stick to one sentence per line (line break only after finished sentences).

Always add a `<!--more-->` for longer articles to not have all text on the main blog site.

**Comment by jakob-r** [comment]
I changed everything, put draft to FALSE, set the date to the 24th of march and rendered it. The post should be then become automatically visible to the public.

**Comment by jakob-r** [comment]
Apparently only the local version of jekyll cares about the publishing date whereas github just publishes articles set to future dates. So I changed to date to today, so that it does not look stange to anybody and your post is published.

**Comment by HeidiSeibold** [comment]
Awesome, thanks! :tada:
