### ISSUE TITLE
We are still not on r-bloggers.com

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr-org.github.io#8]
Maybe because of broken XML in the RSS. @jakob-r said it is fixed, but I don't know if it was really broken and he repaired it or if we still have to change something.
@berndbischl probably should ask Tali about this.

**Comment by berndbischl** [comment]
did you really search on r blogger? 
i just did. the new OML post is online....?

**Comment by berndbischl** [comment]
https://www.r-bloggers.com/mlr-loves-openml/

**Comment by mllg** [comment]
But it is not in the feed.

**Comment by ja-thomas** [comment]
It is,

but the date of the article is "September 8, 2016", so it's already on the second page

https://www.r-bloggers.com/page/2/

**Comment by mllg** [comment]
Nope, not on the website, the generated XML which is parsed by news readers like feedly or theoldreader.

**Comment by berndbischl** [comment]
i emailed talli

**Comment by jakob-r** [comment]
We should see what happens if we publish a new article.
We have to be aware that we should not publish an back-dated article.
That means:
The Date in the Filename YYYY-MM-DD-Title.md should be the date we merge the article.
Otherwise if it's older than the day of the merge the R-Bloggers crawler will see it and put it on the Website but it probably won't appear under the 20 newest posts as it is already outdated on the day we publish it.

**Comment by jakob-r** [comment]
@mllg did it work for the latest post. if so please close

**Comment by berndbischl** [comment]
it worked fine. i will close now
